---
- name: Instalar y configurar Apache en DEVASC
  hosts: localhost
  become: yes
  tasks:

    - name: Instalar Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Cambiar puerto de escucha a 9999
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 9999'

    - name: Cambiar VirtualHost a puerto 9999
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '(<VirtualHost \*:)(80)'
        replace: '\19999'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
