---
- name: Configurar Loopback44 con IPv6 en CSR1000v
  hosts: routers
  gather_facts: no

  tasks:

  - name: Configurar interfaz Loopback44 con IPv6 y link-local
    ios_config:
      lines:
        - interface Loopback44
        - ipv6 address 3001:ABCD:ABCD:4::4/128
        - ipv6 address FE80::1 link-local
